title:              Data Blogger
email:              sumaiyazakirhusen@gmail.com
description:        If you are a data enthusiast then you are at the right place.
author:             Sumaiya Sande
baseurl:            "/blog"
url:                "https://blackrockdigital.github.io"

# Social Profiles
twitter_username:   https://twitter.com/sumaiya_sande
github_username:    https://github.com/sumaiyasande
facebook_username:  https://www.facebook.com/sumaiya.sande
linkedin_username:  https://www.linkedin.com/in/sumaiya-sande-842321134/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
